// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG66qHpfRrLXknr703KoCpQHa4gF7ChhM',
    appId: '1:442868986357:web:6e7d10d4b140e4e55630bc',
    messagingSenderId: '442868986357',
    projectId: 'gem-book-y3-8df25',
    authDomain: 'gem-book-y3-8df25.firebaseapp.com',
    storageBucket: 'gem-book-y3-8df25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFqEgCbNMgaAf4RfKrb_zgYtDqVrZZowQ',
    appId: '1:442868986357:android:5b533b3f6c8c6ab65630bc',
    messagingSenderId: '442868986357',
    projectId: 'gem-book-y3-8df25',
    storageBucket: 'gem-book-y3-8df25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBte3g2uEFZZZEFoC8Y6nc1WbBB7UJyCfY',
    appId: '1:442868986357:ios:cb7dfee3d8a58d605630bc',
    messagingSenderId: '442868986357',
    projectId: 'gem-book-y3-8df25',
    storageBucket: 'gem-book-y3-8df25.appspot.com',
    iosBundleId: 'com.example.gemBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBte3g2uEFZZZEFoC8Y6nc1WbBB7UJyCfY',
    appId: '1:442868986357:ios:94e1c4f69121d4df5630bc',
    messagingSenderId: '442868986357',
    projectId: 'gem-book-y3-8df25',
    storageBucket: 'gem-book-y3-8df25.appspot.com',
    iosBundleId: 'com.example.gemBook.RunnerTests',
  );
}
